name: 'PR labeler based on multiple rules'
description: 'Label Pull Requests based on configurable rules'
author: 'Ryan Harper <ryan.harper@pubicissapient.com>'
inputs: 
  config_path:
    description: 'Path for labeling rules'
    default: '.github/labeler.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: award
  color: blue
